#!/bin/bash
#SBATCH -A pb
#SBATCH -n 128
#SBATCH --tasks-per-node=32
#SBATCH --time=00:30:00 
#SBATCH --error=cores.err
#SBATCH --output=cores.out

module add foss/2019b

mpirun -np 1 ./mergesort 1 120000000
mpirun -np 2 ./mergesort 1 120000000
mpirun -np 4 ./mergesort 1 120000000
mpirun -np 8 ./mergesort 1 120000000
mpirun -np 16 ./mergesort 1 120000000
mpirun -np 32 ./mergesort 1 120000000
mpirun -np 64 ./mergesort 1 120000000
mpirun -np 128 ./mergesort 1 120000000

